title: 'Rongjiehuang/ProDiff'
description: |
  Gradio demo for Rongjiehuang/ProDiff. To use it, simply add your audio, or click one of the examples to load them.
article: |
  Link to <a href='https://github.com/Rongjiehuang/ProDiff' style='color:blue;' target='_blank\'>Github REPO</a>
example_inputs:
  - |-
    the invention of movable metal letters in the middle of the fifteenth century may justly be considered as the invention of the art of printing.
  - |-
    produced the block books, which were the immediate predecessors of the true printed book,
inference_cls: inference.ProDiff_Teacher.ProDiffTeacherInfer
exp_name: ProDiff_Teacher
config: modules/ProDiff/config/prodiff_teacher.yaml